spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true

  datasource:
    url: jdbc:mysql://localhost:3306/chamgyun-in
    username: root
    driver-class-name: com.mysql.jdbc.Driver